// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'config/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> httpGet({
  required String url,
  Value? query,
  AuthHeader? header,
}) => RustLib.instance.api.crateApiRequestsBaseHttpGet(
  url: url,
  query: query,
  header: header,
);

Future<String> httpPost({
  required String url,
  required Value body,
  AuthHeader? header,
}) => RustLib.instance.api.crateApiRequestsBaseHttpPost(
  url: url,
  body: body,
  header: header,
);

Future<String> httpPut({
  required String url,
  required Value body,
  AuthHeader? header,
}) => RustLib.instance.api.crateApiRequestsBaseHttpPut(
  url: url,
  body: body,
  header: header,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Value>>
abstract class Value implements RustOpaqueInterface {}
