name: kikoeru
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^28.2.4
  marquee: ^2.3.0
  just_audio: ^0.9.46
  audio_video_progress_bar: ^2.0.3
  volume_controller: ^3.2.0
  logger: ^2.6.1
  synchronized: ^3.3.1
  audio_service: ^0.18.18
  waterfall_flow: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
