// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/requests/base.dart';
import 'api/requests/config/err.dart';
import 'api/requests/config/types.dart';
import 'api/requests/config/utils.dart';
import 'api/requests/interface.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1175566529;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_kikoeru',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  SortType crateApiRequestsConfigTypesOrdersAutoAccessorGetSort({
    required Orders that,
  });

  void crateApiRequestsConfigTypesOrdersAutoAccessorSetSort({
    required Orders that,
    required SortType sort,
  });

  Future<String> crateApiRequestsConfigErrErrMsg({
    required String url,
    required int code,
    required String msg,
  });

  Future<String> crateApiRequestsInterfaceGetAllWorks({
    int? index,
    int? subtitle,
    int? order,
    AuthHeader? authHeader,
  });

  Future<String> crateApiRequestsInterfaceGetFavoriteWorks({
    int? index,
    AuthHeader? authHeader,
  });

  Future<HeaderMap> crateApiRequestsConfigUtilsGetHeaders({String? token});

  Future<String> crateApiRequestsInterfaceGetPlayList({AuthHeader? authHeader});

  Future<String> crateApiRequestsInterfaceGetPopularWorks({
    int? index,
    int? subtitle,
    AuthHeader? authHeader,
  });

  Future<String> crateApiRequestsInterfaceGetRecommendedWorks({
    int? index,
    int? subtitle,
    AuthHeader? authHeader,
  });

  Future<String> crateApiRequestsInterfaceGetSearchWorks({
    required SearchType searchType,
    String? query,
    int? index,
    int? subtitle,
    int? order,
    AuthHeader? authHeader,
  });

  Future<String> crateApiRequestsInterfaceGetWorkInfo({
    required String id,
    AuthHeader? authHeader,
  });

  Future<String> crateApiRequestsInterfaceGetWorkTrack({
    required String id,
    AuthHeader? authHeader,
  });

  Future<String> crateApiRequestsBaseHttpGet({
    required String url,
    Value? query,
    AuthHeader? header,
  });

  Future<String> crateApiRequestsBaseHttpPost({
    required String url,
    required Value body,
    AuthHeader? header,
  });

  Future<String> crateApiRequestsBaseHttpPut({
    required String url,
    required Value body,
    AuthHeader? header,
  });

  Future<LoginClass> crateApiRequestsConfigTypesLoginClassFromStr({
    required String s,
  });

  Future<String> crateApiRequestsConfigUtilsQueryToString({
    required Map<String, String> query,
  });

  Future<String> crateApiRequestsConfigTypesSearchTypeToParams({
    required SearchType that,
    required String query,
  });

  Future<void> crateApiRequestsConfigTypesSortTypeAsStr({
    required SortType that,
  });

  Future<String> crateApiRequestsConfigTypesSortTypeToStrings({
    required SortType that,
  });

  Future<Env> crateApiRequestsInterfaceTryFetchToken({
    required String account,
    required String password,
  });

  Future<String> crateApiRequestsInterfaceUpdateRate({
    required String id,
    required int rate,
    AuthHeader? authHeader,
  });

  Future<User> crateApiRequestsConfigTypesUserFromStr({required String s});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HeaderMap;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HeaderMap;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_HeaderMapPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Orders;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Orders;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_OrdersPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  SortType crateApiRequestsConfigTypesOrdersAutoAccessorGetSort({
    required Orders that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sort_type,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiRequestsConfigTypesOrdersAutoAccessorGetSortConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiRequestsConfigTypesOrdersAutoAccessorGetSortConstMeta =>
      const TaskConstMeta(
        debugName: "Orders_auto_accessor_get_sort",
        argNames: ["that"],
      );

  @override
  void crateApiRequestsConfigTypesOrdersAutoAccessorSetSort({
    required Orders that,
    required SortType sort,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
            that,
            serializer,
          );
          sse_encode_sort_type(sort, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiRequestsConfigTypesOrdersAutoAccessorSetSortConstMeta,
        argValues: [that, sort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiRequestsConfigTypesOrdersAutoAccessorSetSortConstMeta =>
      const TaskConstMeta(
        debugName: "Orders_auto_accessor_set_sort",
        argNames: ["that", "sort"],
      );

  @override
  Future<String> crateApiRequestsConfigErrErrMsg({
    required String url,
    required int code,
    required String msg,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_u_16(code, serializer);
          sse_encode_String(msg, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigErrErrMsgConstMeta,
        argValues: [url, code, msg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigErrErrMsgConstMeta =>
      const TaskConstMeta(
        debugName: "err_msg",
        argNames: ["url", "code", "msg"],
      );

  @override
  Future<String> crateApiRequestsInterfaceGetAllWorks({
    int? index,
    int? subtitle,
    int? order,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(index, serializer);
          sse_encode_opt_box_autoadd_u_32(subtitle, serializer);
          sse_encode_opt_box_autoadd_u_32(order, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetAllWorksConstMeta,
        argValues: [index, subtitle, order, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetAllWorksConstMeta =>
      const TaskConstMeta(
        debugName: "get_all_works",
        argNames: ["index", "subtitle", "order", "authHeader"],
      );

  @override
  Future<String> crateApiRequestsInterfaceGetFavoriteWorks({
    int? index,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(index, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetFavoriteWorksConstMeta,
        argValues: [index, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetFavoriteWorksConstMeta =>
      const TaskConstMeta(
        debugName: "get_favorite_works",
        argNames: ["index", "authHeader"],
      );

  @override
  Future<HeaderMap> crateApiRequestsConfigUtilsGetHeaders({String? token}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigUtilsGetHeadersConstMeta,
        argValues: [token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigUtilsGetHeadersConstMeta =>
      const TaskConstMeta(debugName: "get_headers", argNames: ["token"]);

  @override
  Future<String> crateApiRequestsInterfaceGetPlayList({
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetPlayListConstMeta,
        argValues: [authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetPlayListConstMeta =>
      const TaskConstMeta(debugName: "get_play_list", argNames: ["authHeader"]);

  @override
  Future<String> crateApiRequestsInterfaceGetPopularWorks({
    int? index,
    int? subtitle,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(index, serializer);
          sse_encode_opt_box_autoadd_u_32(subtitle, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetPopularWorksConstMeta,
        argValues: [index, subtitle, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetPopularWorksConstMeta =>
      const TaskConstMeta(
        debugName: "get_popular_works",
        argNames: ["index", "subtitle", "authHeader"],
      );

  @override
  Future<String> crateApiRequestsInterfaceGetRecommendedWorks({
    int? index,
    int? subtitle,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(index, serializer);
          sse_encode_opt_box_autoadd_u_32(subtitle, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetRecommendedWorksConstMeta,
        argValues: [index, subtitle, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetRecommendedWorksConstMeta =>
      const TaskConstMeta(
        debugName: "get_recommended_works",
        argNames: ["index", "subtitle", "authHeader"],
      );

  @override
  Future<String> crateApiRequestsInterfaceGetSearchWorks({
    required SearchType searchType,
    String? query,
    int? index,
    int? subtitle,
    int? order,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_search_type(searchType, serializer);
          sse_encode_opt_String(query, serializer);
          sse_encode_opt_box_autoadd_u_32(index, serializer);
          sse_encode_opt_box_autoadd_u_32(subtitle, serializer);
          sse_encode_opt_box_autoadd_u_32(order, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetSearchWorksConstMeta,
        argValues: [searchType, query, index, subtitle, order, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetSearchWorksConstMeta =>
      const TaskConstMeta(
        debugName: "get_search_works",
        argNames: [
          "searchType",
          "query",
          "index",
          "subtitle",
          "order",
          "authHeader",
        ],
      );

  @override
  Future<String> crateApiRequestsInterfaceGetWorkInfo({
    required String id,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetWorkInfoConstMeta,
        argValues: [id, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetWorkInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_work_info",
        argNames: ["id", "authHeader"],
      );

  @override
  Future<String> crateApiRequestsInterfaceGetWorkTrack({
    required String id,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceGetWorkTrackConstMeta,
        argValues: [id, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceGetWorkTrackConstMeta =>
      const TaskConstMeta(
        debugName: "get_work_track",
        argNames: ["id", "authHeader"],
      );

  @override
  Future<String> crateApiRequestsBaseHttpGet({
    required String url,
    Value? query,
    AuthHeader? header,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            query,
            serializer,
          );
          sse_encode_opt_box_autoadd_auth_header(header, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsBaseHttpGetConstMeta,
        argValues: [url, query, header],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsBaseHttpGetConstMeta =>
      const TaskConstMeta(
        debugName: "http_get",
        argNames: ["url", "query", "header"],
      );

  @override
  Future<String> crateApiRequestsBaseHttpPost({
    required String url,
    required Value body,
    AuthHeader? header,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            body,
            serializer,
          );
          sse_encode_opt_box_autoadd_auth_header(header, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsBaseHttpPostConstMeta,
        argValues: [url, body, header],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsBaseHttpPostConstMeta =>
      const TaskConstMeta(
        debugName: "http_post",
        argNames: ["url", "body", "header"],
      );

  @override
  Future<String> crateApiRequestsBaseHttpPut({
    required String url,
    required Value body,
    AuthHeader? header,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            body,
            serializer,
          );
          sse_encode_opt_box_autoadd_auth_header(header, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsBaseHttpPutConstMeta,
        argValues: [url, body, header],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsBaseHttpPutConstMeta =>
      const TaskConstMeta(
        debugName: "http_put",
        argNames: ["url", "body", "header"],
      );

  @override
  Future<LoginClass> crateApiRequestsConfigTypesLoginClassFromStr({
    required String s,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_login_class,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigTypesLoginClassFromStrConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigTypesLoginClassFromStrConstMeta =>
      const TaskConstMeta(debugName: "login_class_from_str", argNames: ["s"]);

  @override
  Future<String> crateApiRequestsConfigUtilsQueryToString({
    required Map<String, String> query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Map_String_String_None(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigUtilsQueryToStringConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigUtilsQueryToStringConstMeta =>
      const TaskConstMeta(debugName: "query_to_string", argNames: ["query"]);

  @override
  Future<String> crateApiRequestsConfigTypesSearchTypeToParams({
    required SearchType that,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_search_type(that, serializer);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigTypesSearchTypeToParamsConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigTypesSearchTypeToParamsConstMeta =>
      const TaskConstMeta(
        debugName: "search_type_to_params",
        argNames: ["that", "query"],
      );

  @override
  Future<void> crateApiRequestsConfigTypesSortTypeAsStr({
    required SortType that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_sort_type(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigTypesSortTypeAsStrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigTypesSortTypeAsStrConstMeta =>
      const TaskConstMeta(debugName: "sort_type_as_str", argNames: ["that"]);

  @override
  Future<String> crateApiRequestsConfigTypesSortTypeToStrings({
    required SortType that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_sort_type(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigTypesSortTypeToStringsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigTypesSortTypeToStringsConstMeta =>
      const TaskConstMeta(
        debugName: "sort_type_to_strings",
        argNames: ["that"],
      );

  @override
  Future<Env> crateApiRequestsInterfaceTryFetchToken({
    required String account,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(account, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_env,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceTryFetchTokenConstMeta,
        argValues: [account, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceTryFetchTokenConstMeta =>
      const TaskConstMeta(
        debugName: "try_fetch_token",
        argNames: ["account", "password"],
      );

  @override
  Future<String> crateApiRequestsInterfaceUpdateRate({
    required String id,
    required int rate,
    AuthHeader? authHeader,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_u_32(rate, serializer);
          sse_encode_opt_box_autoadd_auth_header(authHeader, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestsInterfaceUpdateRateConstMeta,
        argValues: [id, rate, authHeader],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsInterfaceUpdateRateConstMeta =>
      const TaskConstMeta(
        debugName: "update_rate",
        argNames: ["id", "rate", "authHeader"],
      );

  @override
  Future<User> crateApiRequestsConfigTypesUserFromStr({required String s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRequestsConfigTypesUserFromStrConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestsConfigTypesUserFromStrConstMeta =>
      const TaskConstMeta(debugName: "user_from_str", argNames: ["s"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HeaderMap =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HeaderMap =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Orders =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Orders =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  HeaderMap
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HeaderMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Orders
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OrdersImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Value
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Orders
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OrdersImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Orders
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OrdersImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  HeaderMap
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HeaderMapImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Orders
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OrdersImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Value
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthHeader dco_decode_auth_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AuthHeader(
      recommenderUuid: dco_decode_opt_String(arr[0]),
      playlistId: dco_decode_opt_String(arr[1]),
      token: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Value
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      raw,
    );
  }

  @protected
  AuthHeader dco_decode_box_autoadd_auth_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_auth_header(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Env dco_decode_env(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Env(
      recommenderUuid: dco_decode_String(arr[0]),
      token: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  LoginClass dco_decode_login_class(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LoginClass(
      user: dco_decode_user(arr[0]),
      token: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Value?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          raw,
        );
  }

  @protected
  AuthHeader? dco_decode_opt_box_autoadd_auth_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_auth_header(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SearchType dco_decode_search_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SearchType.values[raw as int];
  }

  @protected
  SortType dco_decode_sort_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortType.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  User dco_decode_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return User(
      loggedIn: dco_decode_bool(arr[0]),
      name: dco_decode_String(arr[1]),
      group: dco_decode_String(arr[2]),
      email: dco_decode_opt_String(arr[3]),
      recommenderUuid: dco_decode_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  HeaderMap
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HeaderMapImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Orders
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OrdersImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Value
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Orders
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OrdersImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Orders
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OrdersImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  HeaderMap
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HeaderMapImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Orders
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return OrdersImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Value
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthHeader sse_decode_auth_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_recommenderUuid = sse_decode_opt_String(deserializer);
    var var_playlistId = sse_decode_opt_String(deserializer);
    var var_token = sse_decode_opt_String(deserializer);
    return AuthHeader(
      recommenderUuid: var_recommenderUuid,
      playlistId: var_playlistId,
      token: var_token,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Value
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      deserializer,
    ));
  }

  @protected
  AuthHeader sse_decode_box_autoadd_auth_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_auth_header(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Env sse_decode_env(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_recommenderUuid = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    return Env(recommenderUuid: var_recommenderUuid, token: var_token);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  LoginClass sse_decode_login_class(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_user = sse_decode_user(deserializer);
    var var_token = sse_decode_String(deserializer);
    return LoginClass(user: var_user, token: var_token);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Value?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  AuthHeader? sse_decode_opt_box_autoadd_auth_header(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_auth_header(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SearchType sse_decode_search_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SearchType.values[inner];
  }

  @protected
  SortType sse_decode_sort_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortType.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  User sse_decode_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loggedIn = sse_decode_bool(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_group = sse_decode_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_recommenderUuid = sse_decode_String(deserializer);
    return User(
      loggedIn: var_loggedIn,
      name: var_name,
      group: var_group,
      email: var_email,
      recommenderUuid: var_recommenderUuid,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap(
    HeaderMap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HeaderMapImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    Orders self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OrdersImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ValueImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    Orders self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OrdersImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    Orders self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OrdersImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHeaderMap(
    HeaderMap self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HeaderMapImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOrders(
    Orders self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as OrdersImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ValueImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_header(AuthHeader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.recommenderUuid, serializer);
    sse_encode_opt_String(self.playlistId, serializer);
    sse_encode_opt_String(self.token, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_auth_header(
    AuthHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth_header(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_env(Env self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.recommenderUuid, serializer);
    sse_encode_String(self.token, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_login_class(LoginClass self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_user(self.user, serializer);
    sse_encode_String(self.token, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_auth_header(
    AuthHeader? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_auth_header(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_search_type(SearchType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sort_type(SortType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user(User self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.loggedIn, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.group, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_String(self.recommenderUuid, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class HeaderMapImpl extends RustOpaque implements HeaderMap {
  // Not to be used by end users
  HeaderMapImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HeaderMapImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HeaderMap,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HeaderMap,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HeaderMapPtr,
  );
}

@sealed
class OrdersImpl extends RustOpaque implements Orders {
  // Not to be used by end users
  OrdersImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  OrdersImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Orders,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Orders,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_OrdersPtr,
  );

  SortType get sort => RustLib.instance.api
      .crateApiRequestsConfigTypesOrdersAutoAccessorGetSort(that: this);

  set sort(SortType sort) =>
      RustLib.instance.api.crateApiRequestsConfigTypesOrdersAutoAccessorSetSort(
        that: this,
        sort: sort,
      );
}

@sealed
class ValueImpl extends RustOpaque implements Value {
  // Not to be used by end users
  ValueImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ValueImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Value,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Value,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ValuePtr,
  );
}
