// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<HeaderMap> getHeaders({String? token}) =>
    RustLib.instance.api.crateApiRequestsConfigUtilsGetHeaders(token: token);

Future<String> queryToString({required Map<String, String> query}) =>
    RustLib.instance.api.crateApiRequestsConfigUtilsQueryToString(query: query);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HeaderMap>>
abstract class HeaderMap implements RustOpaqueInterface {}
